version: '3.8'

services:
  eureka-server:
    image: kety016/eureka-server:latest  # Eureka Server image
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_APPLICATION_NAME=eureka-server
      - SERVER_PORT=8761
    networks:
      - eureka-network

  trainee-management-service:
    image: kety016/trainee-management-service:latest  # trainee-management-service image
    container_name: trainee-management-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=trainee-management-service
      - SERVER_PORT=8081
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - eureka-server
      - kafka
    networks:
      - eureka-network

  user-management-service:
    image: kety016/usermanagementservice:latest  # user management service image
    container_name: user-management-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_APPLICATION_NAME=user-management-service
      - SERVER_PORT=8083
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - eureka-server
      - kafka
    networks:
      - eureka-network

  email-management-service:
    image: kety016/email-management-service:latest  # email management service image
    container_name: email-management-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_APPLICATION_NAME=email-management-service
      - SERVER_PORT=8086
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - eureka-server
      - kafka
    networks:
      - eureka-network

  api-gateway:
    image: kety016/api-gateway:latest  # API Gateway image
    container_name: api-gateway
    ports:
      - "8093:8093"
    environment:
      - SPRING_APPLICATION_NAME=api-gateway
      - SERVER_PORT=8093
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - eureka-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - eureka-network

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge
