# Application Configuration
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive

  # Cloud Gateway Configuration
  cloud:
    gateway:
      httpclient:
        connect-timeout: 20000
        response-timeout: 7s
      routes:
        # Route to Trainee Management Service
        - id: trainee-management-service
          uri: lb://trainee-management-service
          predicates:
            - Path=/trainees/**

        # Route to User Management Service
        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/users/**

        # Route to User Login Service
        - id: user-login-service
          uri: lb://user-login-service
          predicates:
            - Path=/login/**

        # Route to Email Management Service
        - id: Email-management-service
          uri: lb://Email-management-service
          predicates:
            - Path=/email/**


  # Eureka Client Configuration
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
      instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 30
        lease-expiration-duration-in-seconds: 90

# Server Configuration
server:
  port: 8093

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

# Swagger API Documentation Configuration
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /trainees/v3/api-docs
        name: Trainee Management Service
      - url: /users/v3/api-docs
        name: User Management Service
      - url: /login/v3/api-docs
        name: User Login Service
      - url: /email/v3/api-docs
        name: Email Management Service
