# Configuration for the Eureka server
spring:
  application:
    name: eureka-server

server:
  port: 8761  # Eureka server listens on port 8761

eureka:
  client:
    register-with-eureka: false  # Disable self-registration for the Eureka server
    fetch-registry: false         # Disable registry fetching for the server

logging:
  level:
    com.netflix.eureka: DEBUG     # Temporarily set to DEBUG for troubleshooting
    com.netflix.discovery: DEBUG    # Temporarily set to DEBUG for troubleshooting

---

# Configuration for Service A (Trainee Management Service)
spring:
  config:
    activate:
      on-profile: trainee-management-service

  application:
    name: trainee-management-service

server:
  port: 8081  # Service A listens on port 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Point to Eureka server's URL
    instance:
      prefer-ip-address: true                       # Use IP address for service registration
      lease-renewal-interval-in-seconds: 30       # Heartbeat interval
      lease-expiration-duration-in-seconds: 90      # Expiration time

---

# Configuration for Service C (User Management Service)
spring:
  config:
    activate:
      on-profile: user-management-service

  application:
    name: user-management-service

server:
  port: 8083  # Service C listens on port 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Point to Eureka server's URL
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90

---

# Configuration for Service D (User Login Service)
spring:
  config:
    activate:
      on-profile: user-authentication-service

  application:
    name: user-login-service

server:
  port: 8084  # Service D listens on port 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90

---

# Configuration for API Gateway
spring:
  config:
    activate:
      on-profile: api-gateway

  application:
    name: api-gateway

server:
  port: 8093  # API Gateway listens on port 8093

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90

---

# Configuration for Kafka Producer
spring:
  config:
    activate:
      on-profile: kafka-producer

  application:
    name: kafka-producer

server:
  port: 8094  # Kafka Producer listens on port 8094

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90

---

# Configuration for Kafka Consumer
spring:
  config:
    activate:
      on-profile: kafka-consumer

  application:
    name: kafka-consumer

server:
  port: 8095  # Kafka Consumer listens on port 8095

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true
      lease-renewal-interval-in-seconds: 30
      lease-expiration-duration-in-seconds: 90
