apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-login-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-login
  template:
    metadata:
      labels:
        app: user-login
    spec:
      containers:
        - name: trainee-management
          image: your-docker-repo/user-login-service:latest
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: user-login-service
spec:
  selector:
    app: user-login
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8084
  type: LoadBalancer
